services:
  hgresumable:
    container_name: hgresumable
    build:
      context: csharp
      dockerfile: Dockerfile
    ports:
      - 8034:80
    volumes:
#      use LexBox repo path, adjust as needed for testing.
      - ./../LexBox/hg-web/repos:/var/vcs/public
